B-17237 MilMove Okta Profile Validation
CACI-MIlMOVE/mymove pull request #20
Opened 2023-09-01 14:54 UTC by danieljordan-caci

## [B-17237 Validation for MilMove Profile Information](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A834326&RoomContext=TeamRoom%3A808731&concept=TeamRoom)

## Summary

Added Yup validation schema to Okta Profile Form in MilMove. It checks the following:
- [x] Okta username is in email format
- [x] Okta email is in email format
- [x] First name is required
- [x] Last name is required
- [x] EDIPI is optional, but when inputting it must be between 7-10 digits

If any of these forms do not meet the criteria, it will not allow submission of the form and throw an error.

### Setup to Run the Code

- Pull branch
- `make client_run`
- `make server_run`
- Sign in/register as customer
- Go to profile and scroll down
- Open Okta Profile edit form by clicking "Edit" link
- Input values

2023-09-06 18:35 UTC, cameroncaci commented
Aren't usernames immutable in Okta? If so I'd recommend it being a displayed field but not an editable field

2023-09-06 19:26 UTC, danieljordan-caci commented
> 

Good catch. I have made that field disabled!

2023-09-07 14:22 UTC, cameroncaci requested changes
Proposing new changes

2023-09-07 14:22 UTC, cameroncaci commented on src/utils/validation.js
> +});
Thoughts on replacing these error messages with constants that can be reused in testing? That way the feedback error can always change in the future but the test will always know exactly the error message to be expected.

See line 103 in src/components/Customer/EditOktaInfoForm/EditOktaInfoForm.test.jsx for hard coded error checking

2023-09-07 14:22 UTC, cameroncaci commented on src/utils/validation.js
> +});
Such as these consts in validation.js:
```
export const UnsupportedZipCodeErrorMsg =
  'Sorry, we don’t support that zip code yet. Please contact your local PPPO for assistance.';

export const UnsupportedZipCodePPMErrorMsg =
  "We don't have rates for this ZIP code. Please verify that you have entered the correct one. Contact support if this problem persists.";

export const InvalidZIPTypeError = 'Enter a 5-digit ZIP code';
```

2023-09-07 14:41 UTC, danieljordan-caci commented on src/utils/validation.js
> +});
Did as you said, boss!

2023-09-07 14:45 UTC, cameroncaci requested changes
Variable missed

2023-09-07 14:45 UTC, cameroncaci commented on src/utils/validation.js
>    oktaEmail: Yup.string().email('Invalid email').required('Required'),
Additional const error replacement here

2023-09-07 14:46 UTC, cameroncaci commented on src/utils/validation.js
>    oktaEmail: Yup.string().email('Invalid email').required('Required'),
For the email

2023-09-07 14:53 UTC, danieljordan-caci commented on src/utils/validation.js
>    oktaEmail: Yup.string().email('Invalid email').required('Required'),
Corrected!

2023-09-07 15:04 UTC, cameroncaci approved these changes
Reviewed and actioned 👍

2023-09-07 15:04 UTC, merged