B-17236 Display Profile Values in MilMove Profile Form
CACI-MIlMOVE/mymove pull request #21
Opened 2023-09-06 18:04 UTC by danieljordan-caci

## [B-17236 Display Profile Values in MilMove Profile Form](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A834296&RoomContext=TeamRoom%3A808731&concept=TeamRoom)

## Summary

As a MM customer
I want to see my current Okta Profile data
So I can verify it is accurate

Added Okta profile section for a customer in MilMove that reflects accurate Okta profile information that is retrieved upon login.

Added an API endpoint for `/okta_profile` that returns okta profile data.
Using Redux, storing that data into state
Within appropriate components, pulling that data from state and populating the appropriate text fields

## Verification Steps for the Author

These are to be checked by the author.

- [ ] You are able to log into Customer MilMove (you may need to remove yourself from admin/office groups in Okta)
- [ ] You can see your Okta profile data in the profile edit section

### Setup to Run the Code

- `make client_run`
- `make server_run`
- Log into MilMove as a customer
- Either start/resume your move and navigate to your profile
- You should see your Okta profile information populated in the view/edit text fields

2023-09-06 21:28 UTC, deandreJones approved these changes

2023-09-07 14:20 UTC, cameroncaci requested changes
Requesting changes :)

2023-09-07 14:20 UTC, cameroncaci commented on src/store/entities/selectors.js
> +};
Would recommend renaming existing oktaProfile functions and variables to reflect the state name of oktaUser (Or vice versa). Just to avoid oktaUser and oktaProfile being used interchangeably and to reduce confusion

2023-09-07 14:20 UTC, cameroncaci commented on src/store/entities/selectors.js
> +};
Testing, testing: @danieljordan-caci

2023-09-07 14:42 UTC, danieljordan-caci commented on src/store/entities/selectors.js
> +};
Changed all selectOktaProfile or getOktaProfile in FE to oktaUser. Good suggestion!

2023-09-07 14:52 UTC, cameroncaci commented on src/store/entities/selectors.js
> +};
Backend endpoints as well mention OktaProfile
https://github.com/CACI-MIlMOVE/mymove/blob/5b3e91ba8fab119a2a7c054b84e6d18a5540afcd/pkg/handlers/internalapi/okta_profile.go#L11-L21

https://github.com/CACI-MIlMOVE/mymove/pull/21/files#diff-336c370fa335e12197109741b495e091297b78f3b7715b6190b24d7a0590015aR320-R324

2023-09-07 15:03 UTC, TevinAdams approved these changes

2023-09-07 15:03 UTC, cameroncaci approved these changes
LGTM 👍

2023-09-07 15:03 UTC, merged